### ISSUE TITLE
Missing Leg model on visualisation

### ISSUE THREAD

**Issue by Lzhuoyi** [vincekurtz/drake_ddp#4]
![missing leg](https://github.com/vincekurtz/drake_ddp/assets/169978962/833cbdda-0d60-4dbb-9303-65d378353b22)

![code](https://github.com/vincekurtz/drake_ddp/assets/169978962/b0c4e352-d9f1-4b72-8158-1cbfac31d94a)

I have encountered the problem of missing leg model by running the code... Hope to get your feedback soon!

**Comment by vincekurtz** [comment]
Hi @Lzhuoyi, sorry it took a while to get back to you! It looks like the lower part of the leg was using an older mesh format for the visual geometry. I just pushed a fix (and an update to use the latest version of Drake). Let me know if that doesn't work for you!
